name: Unity Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read 
  checks: write
  pages: write
  
jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      UNITY_SERIAL:   ${{ secrets.UNITY_SERIAL }}
      UNITY_EMAIL:    ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Unity Tests
        uses: game-ci/unity-test-runner@v4
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Build WebGL
        uses: game-ci/unity-builder@v4
        with:
          targetPlatform: WebGL
          allowDirtyBuild: true
          buildPath: build/WebGL

      - name: Deploy Website
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/WebGL



