name: Unity Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Run Edit & Play Mode Tests
        uses: game-ci/unity-test-runner@v4
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          # projectPath: "."
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_SERIAL }}
          
